### ISSUE TITLE
The Journey of an Unsigned Transaction Output

### ISSUE THREAD

**Issue by jasonribble** [AZ-Bitcoin-Network/phoenix-bitdevs-events#10]
I'm working on a presentation describing what the journey of an UTXO actually looks like.

The ideal presentation is dissecting the journey of a newly mined bitcoin from coinbase, to transaction, to broadcast, to validated, and approved into the next block.

How is the coinbase structured?
What do wallets do when they "send bitcoin"?
What types of transactions are there?
What is the general format of a bitcoin transaction?
Why does this matter to a user?
Why does this matter to a developer?

**Comment by jasonribble** [comment]
I'll post some resources that I'll be using.

[Mastering Bitcoin](https://github.com/bitcoinbook/bitcoinbook) for sure 
[Bitcoin Wiki](https://en.bitcoin.it/wiki/Transaction#Types_of_Transaction)

I'll mention the difference between UTXO vs Account-based of course. Probably won't go too deep into the bits and bytes of it all...only a general overview

**Comment by jasonribble** [comment]
[Advanced Bitcoin Scripting part 2](https://www.youtube.com/watch?v=pQbeBduVQ4I) sort of inspired this topic too.

**Comment by bijeebuss** [comment]
Awesome, I’m excited for it

**Comment by jasonribble** [comment]
Here's the [outline](https://github.com/jasonribble/journey-of-an-utxo) of what I have so far @bijeebuss @zantoshi

Still super rough but I'll have something by Friday that's nice; and maybe accompanying slides

**Comment by jasonribble** [comment]
As a note, I want to have this be beginner friendly first, the go to more complex things

**Comment by sntslol** [comment]
Presentation delivered. Closing.
