### ISSUE TITLE
Emerging Features and Best Practices in Mobile Bitcoin Wallets

### ISSUE THREAD

**Issue by micriver** [AZ-Bitcoin-Network/phoenix-bitdevs-events#8]
why this is cool and people should know about it:

Still pretty junior to all this so might be putting the cart before the horse but I've always been interested in it- I want to discuss the industry standards for securing private keys in wallet apps, specifically how new features like warning modals and blurs are being implemented. Are there other lesser-known security features that are becoming standard in new mobile Bitcoin applications?

**Comment by bijeebuss** [comment]
Good idea for a topic. I know there is a lot of nuance when it comes to security tradeoffs in mobile wallets and there is no one right answer for everybody. I tend to be biased towards more "complicated" setups as a tech savvy user so its hard for me to know what onboarding feels like as a new user. Do you want to present something about this at the next meetup?

**Comment by micriver** [comment]
I could definitely cook something up for the next meetup! Never implemented these things in the wild so go easy on me! Just a small presentation?

**Comment by bijeebuss** [comment]
Yeah, like 15 mins and then some time for discussion. Would that be enough?

**Comment by micriver** [comment]
Yes, definitely, I'll come up with something for all levels!

**Comment by sntslol** [comment]
Presentation delivered. Closing.
